version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # Redirige le port 80 d’Nginx vers le port 8080
    volumes:
      - ./nginx/log:/var/log/nginx
    networks:
      - loki-net

  loki:
    image: grafana/loki:2.8.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki:/loki  # Dossier pour stocker les données
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:2.8.1
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - promtail-data:/etc/promtail  # Dossier pour les données de Promtail
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana  # Dossier pour les données de Grafana

networks:
  loki-net:
    driver: bridge

volumes:
  grafana-data:
  loki-data:
  promtail-data:
