auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

  log_level: info

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-10-10
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h  # Changement à 24 heures

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
